name: component
description: "Simple and useful ui components"
version: 0.0.1
homepage: "https://github.com/Lingeshwaran78/Components"

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

